### ISSUE TITLE
Having an icon and a .desktop file

### ISSUE THREAD

**Issue by neelchauhan** [AnsgarKlein/GPG-Gui#2]
I think we should have an icon and a `.desktop` file if we were to market GPG-Gui, and for package maintainers.

I am thinking about creating a FreeBSD Port/package for GPG-Gui, being a "committer" (read: official developer) myself.

However, I am not a designer.

**Comment by Tinram** [comment]
I can't speak for Ansgar.  My own view would be, definitely.

For an icon, seeing your workplace, you must have a lot of talented contacts who might be able to help?
Perhaps something building upon the [GPG padlock](https://twitter.com/gnupg) could be a design starting point?

**Comment by AnsgarKlein** [comment]
Desktop file and icon are absolutely on my todo list. I've just added a minimal .desktop file in 2d8bd8709472928fbcd79dd9ad62f730c9a5d9ff .

I'm also most definitely no designer but give me a few days to try a few things... I think padlocks are an easy way to communicate the applications function since padlocks are used everywhere to indicate encryption.

Regarding FreeBSD: I am no FreeBSD user but would obviously be happy if you would create a package. If there are any other things that need adjusting feel free to open more issues.

**Comment by AnsgarKlein** [comment]
![gpg-gui_128](https://user-images.githubusercontent.com/1733578/104245101-f1ca6200-5463-11eb-943e-9902fec192bb.png)

I have added an application icon in 09b1e17ab921690f98a4ec8558694fb870dc36e2 .

Like I said I am not a designer so that's why the icon looks the way it does. I had hoped I could do better but this will have to do for now. At least there is _an_ icon now.

If anyone wants to contribute a better icon (either based on my attempt or completely new) you are more than welcome to do so but please include an svg.

**Comment by AnsgarKlein** [comment]
Icon and .desktop file are included in v0.2.0
